name: LinxTools
version: '${project.version}'
main: net.ciyuan.linxtools.LinxTools
api-version: '1.21'
load: STARTUP
description: Server Tools.

commands:
  gm:
    description: 切换游戏模式！
    usage: |
      §d切换游戏模式命令用法:
      §b/gm §a0§f为§a生存 §a1§f为§a创造 §a2§f为§a冒险 §a3§f为§a旁观
      §f或者
      §b/gm §a0§f为§a生存 §a1§f为§a创造 §a2§f为§a冒险 §a3§f为§a旁观 §6[玩家]
    permission: linxtools.gamemode
    permission-message: §c明知自己没权限还来搞 ( ͡° ͜ʖ ͡°)
  linx:
    aliases: [linxtools]
    description: 切换游戏模式！
    permission: linxtools.maincommand
    permission-message: §c明知自己没权限还来搞 ( ͡° ͜ʖ ͡°)
  update:
    aliases: [upd, updatedata, updateuserdata]
    description: 切换游戏模式！
    permission: linxtools.update
    permission-message: §c明知自己没权限还来搞 ( ͡° ͜ʖ ͡°)
  suicide:
    aliases: [killme]
    description: 自杀！
    permission: linxtools.suicide
    permission-message: §c明知自己没权限还来搞 ( ͡° ͜ʖ ͡°)
  back:
    aliases: [returntodeath]
    description: 回到死亡地点！
    permission: linxtools.back
    permission-message: §c明知自己没权限还来搞 ( ͡° ͜ʖ ͡°)